### PR TITLE
Add localization via kodi language support

### LINKED ISSUE #39: Enable language support
One of the requirements for kodi addons is that all dialog/settings strings aren't hard-coded but use the kodi language support:
* https://kodi.wiki/view/Language_support
* https://kodi.wiki/view/Add-on_rules#General_requirements

### PR DESCRIPTION
**Pull request by xabgesagtx**
Localize all strings from
* settings
* dialogs
* notifications

Only added German as a second language for now

Fixes #39

### CODE REVIEW

**Comment by czoller** [comment]
#40 comes with a couple of messages, so it might make sense to first finish the other one, rebase that branch, and add translations for the new messages before merging.

**Review by czoller — CHANGES_REQUESTED** [review]
I have rebased and solved the conflicts. Now we need to translate the new stuff.

**Comment by xabgesagtx** [comment]
So, I wanted to add a missing localized text and this created the issue that `str()` was called with a unicode text (German ö). I read that this could be handled with an import from the `future` library (see: http://python-future.org/compatible_idioms.html#unicode).
This will add another dependency but as kodi 19 with python 3 is around the corner it would be removed soonish anyway. 
What do you think?

**Comment by czoller** [comment]
Sounds good.

**Comment by czoller** [comment]
I guess that library should be quite common and already there in most installations.

**Review by czoller — APPROVED** [review]

**Pull request merged**
